/**
 * EAC brand layer — the small wordmark, as its own layer.
 *
 * The wordmark is deliberately *not* part of the installer section: it has its
 * own module, its own slot, its own registration, its own enable flag and its
 * own disposer. Three consequences follow, and all three are the reason for the
 * split:
 *
 *  - a deployment can compose the installer without the brand, or the brand
 *    without the installer, without editing either;
 *  - a build that already fills the sidebar brand row is never fought over —
 *    the layer takes an additive `list` seat instead of a single-occupant one;
 *  - nothing in this file imports the installer, so a fault in the wordmark
 *    cannot take the installation UI down with it.
 *
 * The layer renders text, not an asset: the mark is a wordmark, so it stays
 * legible at rail width, needs no binary in the package, and inherits the
 * surrounding theme through `currentColor` rather than naming any shell token.
 *
 * @module client/brand-layer
 */

import {
  BRAND_LAYER_ID,
  BRAND_LAYER_ORDER,
  BRAND_SLOT_ID,
  BRAND_STYLE_ID,
  BRAND_WORDMARK_ARIA_LABEL,
  EAC_WORDMARK
} from '../protocol.ts'

/** Class name of the wordmark element (plugin-private prefix). */
export const BRAND_WORDMARK_CLASS = `${BRAND_LAYER_ID}__wordmark`

/**
 * The layer's whole stylesheet.
 *
 * Size is the only thing it decides: `font-size` makes the mark *small*, and
 * everything else inherits. Colour comes from `currentColor` and emphasis from
 * `opacity`, so the wordmark follows whatever theme the sidebar is under
 * without this plugin knowing a single official CSS variable name.
 */
export const BRAND_LAYER_CSS = `/* ${BRAND_LAYER_ID} — generated by @dsh-eac/pack-installer; do not edit */
.${BRAND_WORDMARK_CLASS} {
  display: inline-flex;
  align-items: center;
  padding: 0 6px;
  font-size: 10px;
  line-height: 1;
  letter-spacing: 0.08em;
  font-weight: 600;
  text-transform: uppercase;
  color: currentColor;
  opacity: 0.55;
  white-space: nowrap;
  user-select: none;
}
`

/** What one `sidebar.footer.action` registration needs. */
export interface BrandSlotRegistration {
  readonly name: string
  readonly id: string
  readonly order: number
  readonly label: string
}

/** Options of {@link brandSlotRegistration} and {@link registerBrandLayer}. */
export interface BrandLayerOptions {
  /** Set false to compose the client with the installer but without the brand. */
  readonly enabled?: boolean
  /** Wordmark text; defaults to the shared {@link EAC_WORDMARK}. */
  readonly text?: string
}

/**
 * The registration this layer contributes.
 *
 * `sidebar.footer.action` is a `list` seat, so this entry composes *beside* the
 * official occupants. `BRAND_LAYER_ORDER` places it after the official footer
 * actions, keeping the seat's own order meaningful.
 *
 * @returns the registration intent, without touching any context.
 */
export function brandSlotRegistration(): BrandSlotRegistration {
  return { name: BRAND_SLOT_ID, id: BRAND_LAYER_ID, order: BRAND_LAYER_ORDER, label: EAC_WORDMARK }
}

/** The three DOM calls the layer makes — small on purpose, so a fake can stand in. */
export interface BrandElementLike {
  id: string
  className: string
  textContent: string | null
  setAttribute(name: string, value: string): void
}

/** Document surface the layer needs; a real `Document` satisfies it structurally. */
export interface BrandDocumentLike {
  getElementById(id: string): unknown
  createElement(tagName: string): BrandElementLike
  /** `null` in a document without a head, which the layer tolerates. */
  head: { appendChild(node: BrandElementLike): void } | null
}

/**
 * Build the wordmark element.
 *
 * `role="img"` plus the accessible label makes the abbreviation read as one
 * brand mark ("DSH EAC 生态") instead of four letters, which is what a screen
 * reader would otherwise spell out.
 *
 * @param document - document to create the element in.
 * @param options - text override.
 * @returns the element, ready to mount.
 */
export function createWordmarkElement(document: BrandDocumentLike, options: BrandLayerOptions = {}): BrandElementLike {
  const element = document.createElement('span')
  element.id = `${BRAND_LAYER_ID}-wordmark`
  element.className = BRAND_WORDMARK_CLASS
  element.textContent = options.text ?? EAC_WORDMARK
  element.setAttribute('role', 'img')
  element.setAttribute('aria-label', BRAND_WORDMARK_ARIA_LABEL)
  element.setAttribute('title', BRAND_WORDMARK_ARIA_LABEL)
  return element
}

/**
 * Install the layer's stylesheet once, and return its removal.
 *
 * Idempotent by element id, so two mounts (or an HMR re-run) cannot stack style
 * tags, and the returned disposer removes exactly the node this call created —
 * the client-side convention that a plugin's CSS dies with the plugin.
 *
 * @param document - document to install into.
 * @returns disposer removing the style element this call created; a no-op when
 *   the element was already present or the document has no head.
 */
export function installWordmarkStyle(document: BrandDocumentLike): () => void {
  if (document.head === null) return () => {}
  if (document.getElementById(BRAND_STYLE_ID) !== null) return () => {}

  const style = document.createElement('style')
  style.id = BRAND_STYLE_ID
  style.textContent = BRAND_LAYER_CSS
  document.head.appendChild(style)

  let removed = false
  return () => {
    if (removed) return
    removed = true
    const head = document.head as (BrandDocumentLike['head'] & { removeChild?: (node: BrandElementLike) => void }) | null
    head?.removeChild?.(style)
  }
}

/** The slot registry face this layer registers through. */
export interface BrandSlotsLike {
  /** Wait for a declaration, then run the callback; returns the caller-owned disposer. */
  inject(key: string, callback: () => () => void): () => void
  /** Contribute one entry; returns its disposer. */
  register(options: BrandSlotRegistration, component: unknown): () => void
}

/**
 * Compose the brand layer into a client.
 *
 * The occupant is passed in rather than built here, which is what keeps this
 * module free of any renderer: the client entry supplies the component, this
 * module owns the placement, the order, the enable flag and the cleanup.
 *
 * @param slots - the slot registry (`ctx.slots`).
 * @param occupant - the component to render; `undefined` disables the layer.
 * @param options - enable flag and text override.
 * @returns disposer withdrawing the layer; a no-op when it is disabled.
 */
export function registerBrandLayer(slots: BrandSlotsLike, occupant: unknown, options: BrandLayerOptions = {}): () => void {
  if (options.enabled === false || occupant === undefined || occupant === null) return () => {}
  return slots.inject(BRAND_SLOT_ID, () => slots.register(brandSlotRegistration(), occupant))
}
